- name: Install Apache
  apt:
    name: "{{pkg}}"
    state: latest
    update_cache: yes
  become: true

- name: Ensure Apache is started and enabled
  service:
    name: apache2
    state: started
    enabled: yes
  become: true