# - name: Setup Web Server
#   hosts: all
#   become: true
#   vars:
#     apache_action: remove
#   roles:
#     - my_custom_role


- name: Setup Apache Proxy
  hosts: all
  become: true

  roles:
    - proxy_server_role